defaults:
  - model: deepspeech
  - writer: wandb
  - metrics: beam_search_and_argmax
  - datasets: librispeech
  - dataloader: for_3090
  - transforms: example_only_instance
  - _self_
optimizer:
  _target_: torch.optim.AdamW
  lr: 2e-4
lr_scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  max_lr: 4e-4
  pct_start: 0.1
  steps_per_epoch: ${trainer.epoch_len}
  epochs: ${trainer.n_epochs}
  anneal_strategy: cos
loss_function:
  _target_: src.loss.CTCLossWrapper
text_encoder:
  _target_: src.text_encoder.CTCTextEncoder
  vocab_path: /home/ubuntu/dla_asr/src/lm_pretrained/librispeech-vocab.txt
  lm_pretrained_path: /home/ubuntu/dla_asr/src/lm_pretrained/3-gram.pruned.1e-7.arpa
  use_beam_search: True
trainer:
  log_step: 25
  n_epochs: 25
  epoch_len: 100
  max_grad_norm: 10
  use_beam_search: True
  beam_size: 5
  device_tensors: ["spectrogram", "text_encoded"] # which tensors should be on device (ex. GPU)
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: cuda # device name or "auto"
  override: True # if True, will override the previous run with the same name
  monitor: "min val_WER_(BeamSearch)" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 5 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  from_pretrained: /home/ubuntu/dla_asr/saved/deepspeech_fixed_fine_tune_on_other_with_lm_and_beam_search/model_best.pth
  seed: 1
