train:
  get_spectrogram:
      _target_: torchvision.transforms.v2.Compose
      transforms:
        - _target_: torchaudio.transforms.MelSpectrogram
          sample_rate: 16000
        - _target_: src.transforms.spec_augs.FrequencyMasking
          param: 15
          prob: 1
        - _target_: src.transforms.spec_augs.TimeMasking
          param: 30
          prob: 0.15

  audio: # name of the tensor on which we apply transform
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.wav_augs.Gain
      - _target_: src.transforms.wav_augs.HighPassFilter
        prob: 0.3
        max_cutoff_freq: 800
        min_cutoff_freq: 300
        sample_rate: 16000
      - _target_: src.transforms.wav_augs.LowPassFilter
        prob: 0.3
        max_cutoff_freq: 2200
        min_cutoff_freq: 900
        sample_rate: 16000
inference:
  get_spectrogram:
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
